### ISSUE TITLE
Waiting for feedback before PR official docker-library repo

### ISSUE THREAD

**Issue by pierreozoux** [idno/Known-Docker#1]
Ok, now it is your turn :)
I'm waiting your feedback, once collected, I'll PR the official repo.

@benwerd and @erinjo please tell me for:
- LICENSE (it is hte one I usually use, but feel free to put yours)
- Readme
- if it is ok for your to ship facebook plugin and so on (if not, that's also fine)

Cheers!

**Comment by benwerd** [comment]
Awesome! This is brilliant!

Because syndication plugins aren't formally versioned, and this has already caused us issues (in addition to the issues people have setting up the Facebook API etc), let's pull them out of the script.

We also have a version bump already, so I'll add that in the same breadth :)

And finally: Known is Apache licensed, so it probably makes sense to do the same here. If you agree?

**Comment by pierreozoux** [comment]
Ok, these issues are now addressed.

Are we ready to PR the official repo?

**Comment by benwerd** [comment]
I think we are now ready to PR! Exciting!

**Comment by pierreozoux** [comment]
Sorry for the delay, I'm on the process to get piwik official.
Once done, I'll PR known.

(They are equivalent, that's why I'm waiting)

On 16-02-2016 20:04, Ben Werdmuller wrote:

> I think we are now ready to PR! Exciting!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/idno/Known-Docker/issues/1#issuecomment-184856568

## 

I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by benwerd** [comment]
No worries at all! I really appreciate you doing this.

On Thursday, March 3, 2016, Pierre Ozoux notifications@github.com wrote:

> Sorry for the delay, I'm on the process to get piwik official.
> Once done, I'll PR known.
> 
> (They are equivalent, that's why I'm waiting)
> 
> On 16-02-2016 20:04, Ben Werdmuller wrote:
> 
> > I think we are now ready to PR! Exciting!
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/idno/Known-Docker/issues/1#issuecomment-184856568
> 
> ## 
> 
> I use PGP to protect our privacy, if you want to know more, you can
> follow this
> https://emailselfdefense.fsf.org/en/
> 
> If you have further questions, please do not hesitate to ask.
> You can verify my public key here: https://keybase.io/pierreozoux
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/idno/Known-Docker/issues/1#issuecomment-191708633.

## 

Ben Werdmuller
http://goog_1933028737
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by ghost** [comment]
Just a heads-up: I'm new to all this and I don't know a lot about web hosting or Docker, so maybe I'm just missing the obvious.

I don't understand how this is supposed to work:

> For testing purpose, you might want to be able to access the instance from the host without the container's IP, standard port mappings can be used:
> `docker run --link some-mysql:mysql -p 8080:80 -d known`
> Then, access it via http://localhost:8080 or http://host-ip:8080 in a browser.

There is no web server, is there? The solution would be to offer one image based on php-apache and one image based on php-fpm, just like the guys from wordpress or owncloud are doing it.

**Comment by pierreozoux** [comment]
@IKSGroth yes you are right, I updated the README to reflect that.
If you want to add an apache image, please feel free to PR :)

In the mean time, I finally found time to PR to make it an official image \o/

https://github.com/docker-library/official-images/pull/1763

**Comment by pierreozoux** [comment]
@benwerd can you put your support on the official PR please (link above)? I don't know why, it is taking time :)
