### ISSUE TITLE
Can't Access Known on a kubernetes cluster

### ISSUE THREAD

**Issue by Kemsty2** [idno/Known-Docker#10]
Hi, I've been trying to deploy known on my kubernetes cluster since then, but I can't access the service. 
First of all, I would like to know on which port Known communicates, 
Here is my configuration file and log file
![capture d ecran_2018-09-22_15-20-51](https://user-images.githubusercontent.com/32348054/45918237-d0e93780-be7b-11e8-8266-6e22dfb0ef3a.png)
[known_deploy_file.txt](https://github.com/idno/Known-Docker/files/2407855/known_deploy_file.txt)

**Comment by pierreozoux** [comment]
Hello!

Many mistakes here, but I can help!

This docker image uses PHP-FPM, read some documentation about it.
The important bit is that it doesn't speak http. So you need an http server in front, like nginx.

Don't expose mysql!

Don't put everything on the same pod., mysql, known and nginx should be on different pods, and discuss over services.

Check the official wordpress example https://github.com/helm/charts/tree/master/stable/wordpress
It might help you!

Good luck, and ask questions here, hope I can help!

**Comment by mapkyca** [comment]
Gonna close, reopen if still an issue
