### ISSUE TITLE
Support 0.9.9

### ISSUE THREAD

**Issue by cweiske** [idno/Known-Docker#2]
https://hub.docker.com/r/library/known/tags/ still has 0.9.2 as most up-to-date version. Please support 0.9.9 (https://groups.google.com/forum/#!topic/known-dev/UXPHVXBmshQ).

**Comment by pierreozoux** [comment]
@benwerd could you add: https://github.com/docker-library-bot to the collaborators, then the process would be automatised.
Thanks!

**Comment by mapkyca** [comment]
Looks like this was done in 676e8a4

**Comment by edrex** [comment]
A new image built from the dockerfile still needs to uploaded to the registry: https://hub.docker.com/_/known/

+1 for automation :D

**Comment by edrex** [comment]
It seems like something is wrong with the build bot config. When I click the "Dockerfile" link next to "latest" on https://hub.docker.com/r/library/known/, it points to an old ref from 2016.  The bot is building new images, but they seem to be pinned to that ref. IDK where in the various @docker-library metadata repos this ref is set. @pierreozoux any ideas?

**Comment by edrex** [comment]
Ah here we go: https://github.com/docker-library/official-images/blob/master/library/known needs to be updated.

**Comment by pierreozoux** [comment]
@benwerd or @mapkyca could you add: https://github.com/docker-library-bot to the collaborators, then the process would be automatised.
Thanks!

**Comment by edrex** [comment]
For now I've forked this repo and set up an auto builder for my own use. https://hub.docker.com/r/pdxhub/known/

**Comment by mapkyca** [comment]
@pierreozoux ... you mean to the Known-Docker project?

**Comment by mapkyca** [comment]
... don't we just need to set up the integration..? https://docs.docker.com/docker-hub/builds/#understand-the-build-process ... or am I misunderstanding you :) (little troubled by giving third party accounts repo access, bot or no... seems like a bad way of automating something...)

**Comment by mapkyca** [comment]
I think we just need to activate the docker hub service on the github side, in which case I'll need @benwerd to do it as he has the docker account it needs to go under.

I'll give him a ping...

**Comment by pierreozoux** [comment]
Sorry that it was not clear.
It is the automation process for official images.
(for regular images, yes, then you use the docker automated builds)

For the official images, you give access to a bot that can commit on this repo.
(I think it is a Jenkins repo)

It then runs once a day I think to run the `update.sh` script and figure out if there is a new version.
If there is, then it updates the Dockerfile.
And at the end, it generates the stackbrew library that is used to tag the official images.

So it is really cool, as the full process is automated. You see what I mean now?
If you need details, let me know.

**Comment by pierreozoux** [comment]
@mapkyca any news on that please?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known-Docker/issues/2" class="u-in-reply-to"></a>I've given the bot read access to the repo, currently awaiting a response... not sure how long that will take...

**Comment by rmdes** [comment]
any news on this ?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known-Docker/issues/2" class="u-in-reply-to"></a>I added the bot as a contributor, I'm not sure what happens next..

**Comment by pierreozoux** [comment]
The bot needs write access.
@J0WI could you help us on that please?

**Comment by J0WI** [comment]
>  @J0WI could you help us on that please?

I'm not sure how?

**Comment by J0WI** [comment]
I just had a look on the Dockerfile and it's currently broken. I would highly recommend to add a CI to the repo that you are aware of any failures.
A PR to fix the build is right around the corner.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known-Docker/issues/2" class="u-in-reply-to"></a>I've enabled write access.

**Comment by J0WI** [comment]
https://github.com/docker-library/official-images/blob/master/library/known should be updated

**Comment by mapkyca** [comment]
Assuming this is fixed now, closing
