### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [idno/Known-Docker#3]
I want to build this image on arm64 architecture but I don't know that http://assets.withknown.com/releases/known-0.9.2.zip whether or not support arm64 architecture.

**Comment by mapkyca** [comment]
If PHP and Apache both run on arm64 then there's nothing inside Known that'd prevent it from running....

**Comment by odidev** [comment]
Hi,

Is there any way that this repository can officially support ```arm64v8``` architecture?
I can test and provide logs if required.

In addition, I can raise a PR if required to include ```arm64v8```.

Regards,

**Comment by pierreozoux** [comment]
@odidev please PR :)

You can follow this guide to do so:
https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by odidev** [comment]
Thanks @pierreozoux 
BTW, What should be ```Maintainers:``` name for library file ?

**Comment by odidev** [comment]
@pierreozoux - Raised PR, as per your guidance :smile:

**Comment by odidev** [comment]
```known``` is working very well on ```arm64v8```.

And this works with ```docker pull``` too.
In my view, this ticket can be closed now.

**Comment by mapkyca** [comment]
Thanks for your help!
