### ISSUE TITLE
ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by jamesalbert** [idno/Known-Docker#6]
Tried running this with: `docker run -p 8080:9000 -e KNOWN_DB_PASSWORD=test -d known` and am getting an empty response. Am I missing anything?

edit: realized my initial post was totally vague and unhelpful. I'm running:

MacOs High Sierra 10.13
Docker 18.03.1-ce

and the output from docker logs is:
```
Cannot connect to Mysql. Starting anyway...
[06-May-2018 23:02:11] NOTICE: fpm is running, pid 1
[06-May-2018 23:02:11] NOTICE: ready to handle connections
```

This always happens for me even when I have a mysql instance up, but this was the simplest example with the issue.

**Comment by pierreozoux** [comment]
this is starting an fpm process, you'd need to put a web server in front.

There is a link to a docker-compose with some examples.

Let me know if you still have troubles.
