### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by odidev** [idno/Known-Docker#9]
I am trying to use ```postgreSQL``` for ```known``` package.

But, I can notice that known has serious dependency on ```MYSQL``` package and it gives below error even when I link ```postgres``` container:

```Connecting to database..........Cannot connect to Mysql. Starting anyway...```

Does ```Known``` support ```PostgreSQL```?

**Comment by mapkyca** [comment]
Known core supports Postgres, but I suspect the docker image would need some modification to load the correct config and apply the appropriate schema

**Comment by odidev** [comment]
@mapkyca: Thanks, Can you please suggest relevant changes which can be done to use ```postgres``` instead of ```mysql```.

I am open to do experimental changes too.

Regards,

**Comment by odidev** [comment]
If ```PostgreSQL``` works with ```known``` then we can go ahead to add support for ```arm64v8``` as well.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Known-Docker/issues/9#issuecomment-409612469" class="u-in-reply-to"></a>Main thing is you need to set ```database = 'Postgres'``` in your config.ini. Then install the schema by hand, as the installer currently won't do this for you.

**Comment by odidev** [comment]
Thanks for the information and support.
Known is now ```docker pull```able over ```arm64v8```.

Closing the ticket now.
